/*
 * To change this license header, choose License Headers in Project Properties.
 * To change this template file, choose Tools | Templates
 * and open the template in the editor.
 */
package proyect;

import conek.nek;
import java.awt.*;
import java.sql.*;
import java.sql.Connection;
import java.sql.ResultSet;
import java.sql.Statement;
import javax.swing.JOptionPane;
import javax.swing.SwingUtilities;
import java.sql.SQLException;
import java.util.Random;
import java.util.concurrent.TimeUnit;
import panel.pJual;

/**
 *
 * @author ASUS
 */
public class Form_Login extends javax.swing.JFrame {

    String sql, checkUser = null;
    Graphics a, b;

    /**
     * Creates new form login
     */
    public Form_Login() {
        initComponents();
        setBackground(new Color(0.0f, 0.0f, 0.0f, 0.0f));
        this.setLocationRelativeTo(null);
        SwingUtilities.getRootPane(btLogin).setDefaultButton(btLogin);
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        border1 = new panel.Border();
        btOut = new javax.swing.JButton();
        btLogin = new javax.swing.JButton();
        welcome = new javax.swing.JLabel();
        jLabel2 = new javax.swing.JLabel();
        txtUser = new javax.swing.JTextField();
        jLabel3 = new javax.swing.JLabel();
        txtPass = new javax.swing.JPasswordField();
        jLabel1 = new javax.swing.JLabel();
        jSeparator1 = new javax.swing.JSeparator();
        jSeparator2 = new javax.swing.JSeparator();
        border2 = new panel.Border();

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);
        setUndecorated(true);
        getContentPane().setLayout(new org.netbeans.lib.awtextra.AbsoluteLayout());

        border1.setBackground(new java.awt.Color(49, 49, 49));

        btOut.setBackground(new java.awt.Color(51, 51, 51));
        btOut.setFont(new java.awt.Font("Yu Gothic UI", 1, 14)); // NOI18N
        btOut.setForeground(new java.awt.Color(255, 255, 255));
        btOut.setIcon(new javax.swing.ImageIcon(getClass().getResource("/img/x-mark-32.png"))); // NOI18N
        btOut.setBorderPainted(false);
        btOut.setContentAreaFilled(false);
        btOut.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btOutActionPerformed(evt);
            }
        });
        border1.add(btOut, new org.netbeans.lib.awtextra.AbsoluteConstraints(170, 260, 100, 40));

        btLogin.setBackground(new java.awt.Color(51, 51, 51));
        btLogin.setFont(new java.awt.Font("Yu Gothic UI", 1, 14)); // NOI18N
        btLogin.setForeground(new java.awt.Color(255, 255, 255));
        btLogin.setIcon(new javax.swing.ImageIcon(getClass().getResource("/img/key-48.png"))); // NOI18N
        btLogin.setBorderPainted(false);
        btLogin.setContentAreaFilled(false);
        btLogin.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btLoginActionPerformed(evt);
            }
        });
        border1.add(btLogin, new org.netbeans.lib.awtextra.AbsoluteConstraints(60, 250, 100, -1));

        welcome.setBackground(new java.awt.Color(250, 249, 247));
        welcome.setFont(new java.awt.Font("Carlito", 1, 48)); // NOI18N
        welcome.setForeground(new java.awt.Color(250, 249, 247));
        welcome.setText("WELCOME");
        border1.add(welcome, new org.netbeans.lib.awtextra.AbsoluteConstraints(60, 60, -1, -1));

        jLabel2.setBackground(new java.awt.Color(250, 249, 247));
        jLabel2.setFont(new java.awt.Font("Yu Gothic UI", 1, 14)); // NOI18N
        jLabel2.setForeground(new java.awt.Color(250, 249, 247));
        jLabel2.setText("Username");
        border1.add(jLabel2, new org.netbeans.lib.awtextra.AbsoluteConstraints(60, 160, -1, -1));

        txtUser.setBackground(new java.awt.Color(49, 49, 49));
        txtUser.setFont(new java.awt.Font("Yu Gothic UI", 0, 12)); // NOI18N
        txtUser.setForeground(new java.awt.Color(250, 249, 247));
        txtUser.setBorder(null);
        border1.add(txtUser, new org.netbeans.lib.awtextra.AbsoluteConstraints(60, 180, 210, 20));

        jLabel3.setBackground(new java.awt.Color(250, 249, 247));
        jLabel3.setFont(new java.awt.Font("Yu Gothic UI", 1, 14)); // NOI18N
        jLabel3.setForeground(new java.awt.Color(250, 249, 247));
        jLabel3.setText("Password");
        border1.add(jLabel3, new org.netbeans.lib.awtextra.AbsoluteConstraints(60, 210, -1, -1));

        txtPass.setBackground(new java.awt.Color(49, 49, 49));
        txtPass.setFont(new java.awt.Font("Yu Gothic UI", 0, 12)); // NOI18N
        txtPass.setForeground(new java.awt.Color(250, 249, 247));
        txtPass.setBorder(null);
        border1.add(txtPass, new org.netbeans.lib.awtextra.AbsoluteConstraints(60, 230, 210, 20));

        jLabel1.setIcon(new javax.swing.ImageIcon(getClass().getResource("/img/cash.gif"))); // NOI18N
        border1.add(jLabel1, new org.netbeans.lib.awtextra.AbsoluteConstraints(320, 0, -1, -1));

        jSeparator1.setBackground(new java.awt.Color(250, 249, 247));
        border1.add(jSeparator1, new org.netbeans.lib.awtextra.AbsoluteConstraints(60, 250, 210, 10));

        jSeparator2.setBackground(new java.awt.Color(250, 249, 247));
        border1.add(jSeparator2, new org.netbeans.lib.awtextra.AbsoluteConstraints(60, 200, 210, 20));

        getContentPane().add(border1, new org.netbeans.lib.awtextra.AbsoluteConstraints(0, 0, 640, 440));

        border2.setBackground(new java.awt.Color(102, 51, 255));

        javax.swing.GroupLayout border2Layout = new javax.swing.GroupLayout(border2);
        border2.setLayout(border2Layout);
        border2Layout.setHorizontalGroup(
            border2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGap(0, 640, Short.MAX_VALUE)
        );
        border2Layout.setVerticalGroup(
            border2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGap(0, 440, Short.MAX_VALUE)
        );

        getContentPane().add(border2, new org.netbeans.lib.awtextra.AbsoluteConstraints(0, 0, 640, 440));

        setSize(new java.awt.Dimension(640, 440));
        setLocationRelativeTo(null);
    }// </editor-fold>//GEN-END:initComponents

    private void btLoginActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btLoginActionPerformed
        try {
            String sql = "select id_user, akses from user where username='" + txtUser.getText() + "' and password='" + txtPass.getText() + "'";

            java.sql.Connection conn = (Connection) nek.configDB();
            java.sql.Statement stm = conn.createStatement();
            java.sql.ResultSet res = stm.executeQuery(sql);

            if (res.next()) {
                String st = res.getString("akses");
                System.out.println(st);
                if (st.equalsIgnoreCase("admin")) {
                    Form_MenuA amen = new Form_MenuA();
                    amen.show();
                    amen.nama.setText(txtUser.getText());
                    pJual.txtID.setText(res.getString(1));
                    this.hide();
                } else if (st.equalsIgnoreCase("kasir")) {
                    Form_MenuK men = new Form_MenuK();
                    men.show();
                    men.nama.setText(txtUser.getText());
                    pJual.txtID.setText(res.getString(1));
                    this.hide();
                }
            } else {
                JOptionPane.showMessageDialog(null, "Username/Password salah, coba lagi.", "", JOptionPane.ERROR_MESSAGE);
                txtPass.setText(null);
                txtPass.requestFocus();
            }
        } catch (SQLException e) {
            System.out.println("Error" + e.getMessage());
        }
    }//GEN-LAST:event_btLoginActionPerformed

    private void btOutActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btOutActionPerformed
        int cus = JOptionPane.showConfirmDialog(null,
                "Keluar dari aplikasi?",
                "Konfirmasi", JOptionPane.OK_CANCEL_OPTION);

        if (cus == JOptionPane.OK_OPTION) {
            System.exit(0);
        } else {
            JOptionPane.getRootFrame();
        }
    }//GEN-LAST:event_btOutActionPerformed

    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(Form_Login.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(Form_Login.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(Form_Login.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(Form_Login.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>
        //</editor-fold>
        //</editor-fold>
        //</editor-fold>

        /* Create and display the form */
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                new Form_Login().setVisible(true);
            }
        });
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private panel.Border border1;
    private panel.Border border2;
    private javax.swing.JButton btLogin;
    private javax.swing.JButton btOut;
    private javax.swing.JLabel jLabel1;
    private javax.swing.JLabel jLabel2;
    private javax.swing.JLabel jLabel3;
    private javax.swing.JSeparator jSeparator1;
    private javax.swing.JSeparator jSeparator2;
    private javax.swing.JPasswordField txtPass;
    private javax.swing.JTextField txtUser;
    private javax.swing.JLabel welcome;
    // End of variables declaration//GEN-END:variables
}
