/*
 * To change this license header, choose License Headers in Project Properties.
 * To change this template file, choose Tools | Templates
 * and open the template in the editor.
 */
package panel;

import conek.nek;
import java.awt.Color;
import java.awt.HeadlessException;
import java.sql.Connection;
import java.sql.SQLException;
import javax.swing.JOptionPane;
import javax.swing.table.DefaultTableModel;
import javax.swing.table.TableColumn;
import raven.cell.TableActionCellEditor;
import raven.cell.TableActionCellRender;
import raven.cell.TableActionEvent;
import proyect.Form_MenuA;

/**
 *
 * @author ASUS
 */
public class pAbout extends javax.swing.JPanel {

    /**
     * Creates new form pUser
     */
    public pAbout() {
        initComponents();
        setOpaque(false);
        setBackground(new Color(39, 36, 29, 0));
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        border1 = new panel.Border();
        jLabel1 = new javax.swing.JLabel();
        jScrollPane1 = new javax.swing.JScrollPane();
        jTextArea1 = new javax.swing.JTextArea();

        setLayout(new org.netbeans.lib.awtextra.AbsoluteLayout());

        jLabel1.setFont(new java.awt.Font("Carlito", 1, 24)); // NOI18N
        jLabel1.setForeground(new java.awt.Color(250, 249, 247));
        jLabel1.setText("Designed by William, Frendly and Maria.");
        border1.add(jLabel1, new org.netbeans.lib.awtextra.AbsoluteConstraints(70, 50, -1, -1));

        jScrollPane1.setBorder(null);

        jTextArea1.setBackground(new java.awt.Color(39, 36, 29));
        jTextArea1.setColumns(20);
        jTextArea1.setFont(new java.awt.Font("Carlito", 0, 18)); // NOI18N
        jTextArea1.setForeground(new java.awt.Color(250, 249, 247));
        jTextArea1.setRows(5);
        jTextArea1.setText("We are a leading technology company specializing in software development, web development, \nand digital marketing. Our mission is to drive digital transformation and empower businesses to \nthrive in the digital age. With our expertise and commitment to quality, we deliver innovative \nsolutions that help organizations stay ahead in the ever-evolving digital landscape.\n\nContact us today to discuss your project requirements or schedule a consultation. \nLet's unlock your business's full potential together!");
        jTextArea1.setBorder(null);
        jScrollPane1.setViewportView(jTextArea1);

        border1.add(jScrollPane1, new org.netbeans.lib.awtextra.AbsoluteConstraints(70, 90, 710, 180));

        add(border1, new org.netbeans.lib.awtextra.AbsoluteConstraints(0, 0, 920, 370));
    }// </editor-fold>//GEN-END:initComponents


    // Variables declaration - do not modify//GEN-BEGIN:variables
    private panel.Border border1;
    private javax.swing.JLabel jLabel1;
    private javax.swing.JScrollPane jScrollPane1;
    private javax.swing.JTextArea jTextArea1;
    // End of variables declaration//GEN-END:variables
}
