/*
 * To change this license header, choose License Headers in Project Properties.
 * To change this template file, choose Tools | Templates
 * and open the template in the editor.
 */
package panel;

import conek.nek;
import java.awt.Color;
import java.awt.HeadlessException;
import java.sql.Connection;
import java.sql.SQLException;
import javax.swing.JOptionPane;
import javax.swing.table.DefaultTableModel;
import javax.swing.table.TableColumn;
import raven.cell.TableActionCellEditor;
import raven.cell.TableActionCellRender;
import raven.cell.TableActionEvent;
import proyect.Form_MenuA;
import proyect.Form_MenuK;

/**
 *
 * @author ASUS
 */
public class pPass extends javax.swing.JPanel {

    /**
     * Creates new form pUser
     */
    public pPass() {
        initComponents();
        setOpaque(false);
        setBackground(new Color(39, 36, 29, 0));
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        border1 = new panel.Border();
        jLabel1 = new javax.swing.JLabel();
        jLabel2 = new javax.swing.JLabel();
        jLabel3 = new javax.swing.JLabel();
        jSeparator1 = new javax.swing.JSeparator();
        jSeparator2 = new javax.swing.JSeparator();
        jSeparator3 = new javax.swing.JSeparator();
        btPass = new javax.swing.JLabel();
        txtPassLama = new javax.swing.JTextField();
        txtPassBaru = new javax.swing.JTextField();
        txtPassBar = new javax.swing.JTextField();

        setLayout(new org.netbeans.lib.awtextra.AbsoluteLayout());

        jLabel1.setFont(new java.awt.Font("Carlito", 1, 24)); // NOI18N
        jLabel1.setForeground(new java.awt.Color(250, 249, 247));
        jLabel1.setHorizontalAlignment(javax.swing.SwingConstants.LEFT);
        jLabel1.setText("Konfirmasi Password baru :");
        border1.add(jLabel1, new org.netbeans.lib.awtextra.AbsoluteConstraints(30, 230, 280, -1));

        jLabel2.setFont(new java.awt.Font("Carlito", 1, 24)); // NOI18N
        jLabel2.setForeground(new java.awt.Color(250, 249, 247));
        jLabel2.setHorizontalAlignment(javax.swing.SwingConstants.LEFT);
        jLabel2.setText("Password lama :");
        border1.add(jLabel2, new org.netbeans.lib.awtextra.AbsoluteConstraints(30, 50, 170, -1));

        jLabel3.setFont(new java.awt.Font("Carlito", 1, 24)); // NOI18N
        jLabel3.setForeground(new java.awt.Color(250, 249, 247));
        jLabel3.setHorizontalAlignment(javax.swing.SwingConstants.LEFT);
        jLabel3.setText("Password baru :");
        border1.add(jLabel3, new org.netbeans.lib.awtextra.AbsoluteConstraints(30, 140, 170, -1));

        jSeparator1.setBackground(new java.awt.Color(250, 249, 247));
        border1.add(jSeparator1, new org.netbeans.lib.awtextra.AbsoluteConstraints(40, 110, 210, 10));

        jSeparator2.setBackground(new java.awt.Color(250, 249, 247));
        border1.add(jSeparator2, new org.netbeans.lib.awtextra.AbsoluteConstraints(40, 200, 210, 10));

        jSeparator3.setBackground(new java.awt.Color(250, 249, 247));
        border1.add(jSeparator3, new org.netbeans.lib.awtextra.AbsoluteConstraints(40, 290, 210, 10));

        btPass.setFont(new java.awt.Font("Carlito", 1, 30)); // NOI18N
        btPass.setForeground(new java.awt.Color(66, 61, 51));
        btPass.setIcon(new javax.swing.ImageIcon(getClass().getResource("/img/edit-48.png"))); // NOI18N
        btPass.setAutoscrolls(true);
        btPass.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                btPassMouseClicked(evt);
            }
            public void mouseReleased(java.awt.event.MouseEvent evt) {
                btPassMouseReleased(evt);
            }
        });
        border1.add(btPass, new org.netbeans.lib.awtextra.AbsoluteConstraints(850, 300, 50, -1));

        txtPassLama.setBackground(new java.awt.Color(39, 36, 29));
        txtPassLama.setFont(new java.awt.Font("Carlito", 0, 14)); // NOI18N
        txtPassLama.setForeground(new java.awt.Color(250, 249, 247));
        txtPassLama.setBorder(null);
        border1.add(txtPassLama, new org.netbeans.lib.awtextra.AbsoluteConstraints(40, 90, 210, 20));

        txtPassBaru.setBackground(new java.awt.Color(39, 36, 29));
        txtPassBaru.setFont(new java.awt.Font("Carlito", 0, 14)); // NOI18N
        txtPassBaru.setForeground(new java.awt.Color(250, 249, 247));
        txtPassBaru.setBorder(null);
        border1.add(txtPassBaru, new org.netbeans.lib.awtextra.AbsoluteConstraints(40, 180, 210, 20));

        txtPassBar.setBackground(new java.awt.Color(39, 36, 29));
        txtPassBar.setFont(new java.awt.Font("Carlito", 0, 14)); // NOI18N
        txtPassBar.setForeground(new java.awt.Color(250, 249, 247));
        txtPassBar.setBorder(null);
        border1.add(txtPassBar, new org.netbeans.lib.awtextra.AbsoluteConstraints(40, 270, 210, 20));

        add(border1, new org.netbeans.lib.awtextra.AbsoluteConstraints(0, 0, 920, 370));
    }// </editor-fold>//GEN-END:initComponents

    private void btPassMouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_btPassMouseClicked
        // TODO add your handling code here:
    }//GEN-LAST:event_btPassMouseClicked

    private void btPassMouseReleased(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_btPassMouseReleased
        try {
            String sql = "select * from user where username='" + Form_MenuA.nama.getText() + "' and password='" + txtPassLama.getText() + "'";

            java.sql.Connection conn = (Connection) nek.configDB();
            java.sql.Statement stm = conn.createStatement();
            java.sql.ResultSet res = stm.executeQuery(sql);

            if (res.next()) {
                if (txtPassBar.getText() != txtPassBaru.getText()) {
                    JOptionPane.showMessageDialog(null, "Password baru tidak cocok, coba lagi!", "", JOptionPane.ERROR_MESSAGE);
                    txtPassBar.requestFocus();
                } else {
                    try {
                        String sq = "update user set password='" + txtPassBar.getText() + "' where username='" + Form_MenuA.nama.getText() + "'";

                        java.sql.Connection con = (Connection) nek.configDB();
                        java.sql.Statement st = conn.createStatement();
                        java.sql.ResultSet re = stm.executeQuery(sq);

                        JOptionPane.showMessageDialog(null, "Password berhasil diubah!");
                    } catch (SQLException e) {
                        JOptionPane.showMessageDialog(null, "Gagal", "", JOptionPane.ERROR_MESSAGE);
                    }
                }
            } else {
                JOptionPane.showMessageDialog(null, "Username/Password salah, coba lagi.", "", JOptionPane.ERROR_MESSAGE);
                txtPassLama.setText(null);
                txtPassBaru.setText(null);
                txtPassBar.setText(null);
                txtPassLama.requestFocus();
            }
        } catch (SQLException e) {
            System.out.println("Error" + e.getMessage());
        }
    }//GEN-LAST:event_btPassMouseReleased


    // Variables declaration - do not modify//GEN-BEGIN:variables
    private panel.Border border1;
    private javax.swing.JLabel btPass;
    private javax.swing.JLabel jLabel1;
    private javax.swing.JLabel jLabel2;
    private javax.swing.JLabel jLabel3;
    private javax.swing.JSeparator jSeparator1;
    private javax.swing.JSeparator jSeparator2;
    private javax.swing.JSeparator jSeparator3;
    private javax.swing.JTextField txtPassBar;
    private javax.swing.JTextField txtPassBaru;
    private javax.swing.JTextField txtPassLama;
    // End of variables declaration//GEN-END:variables
}
